/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secretaria;

import Clases.ManejadorValidar;
import Clases.PersonalManejador;
import Clases.SolictudesManejador;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author tepic
 */
public class NuevaSolicitud extends javax.swing.JFrame {
    int fila;
    int error;
    int fila2;
    String id_chofer="";
    String estapernotando="";
String incluidoVehiculo="";
String idVehiculo="";
String chofer="";
SolictudesManejador manejador;
String id_per="";
boolean m;
Date date= new Date();
int tipo;


    /**
     * Creates new form NuevaSolicitud
     */
    public NuevaSolicitud() {
        
        initComponents();
         manejador= new SolictudesManejador();
        m=true;
        this.setLocationRelativeTo(null);
        
    }
    
    public void esChofer(){
        
        if(choferCheck.isSelected()){
            chofer="SI";
            tipo=0;
        }else{
            chofer="NO";
            tipo=1;
        }
    }
    
    public void pernotaValida(){
        if(siPernota.isSelected()==true){
        estapernotando="si";
       
        
        }if(noPernota.isSelected()==true){
            estapernotando="no";
        
             
        }
    }
    
    public void setChofer(String id){
        this.id_chofer=id;
    }
    
    public void validaVehi(){
        if(necesario.isSelected()){
            incluidoVehiculo="si";
        }else{
            incluidoVehiculo="no";
        }
    }
    
    public boolean error(){
        boolean pase=true;
        if(fecha1.getCalendar()==null){
            error=1;
            
            pase=false;
            
        }
        if(fecha2.getCalendar()==null){
            error=2;
            
            pase=false;
            
        }
        
        if(siPernota.isSelected()==false && noPernota.isSelected()==false){
            error=3;
            pase=false;
        }
        if(seleccionadoE.getText().equals("X")){
            error=4;
            pase=false;
        }
        
        if(campoActividad.getText()==""){{
            error=5;
            pase=false;
        }
        if(campoLugar.getText()==""){
            error=6;
            pase=false;
        }
        
        
    }if(necesario.isSelected()==false && choferCheck.isSelected()==true){
        error=8;
        pase=false;
        
    }if(fecha1.getDate().after(date)==false){
        error=9;
        pase=false;
    }if(fecha2.getDate().after(fecha1.getDate())==false){
        error=10;
        pase=false;
    }
    
    
    return pase;
           
    }
    
    public void ManejadorError(int errorTipo){
        switch(errorTipo){
            case 1:
                JOptionPane.showMessageDialog(this, "Fecha inicial vacia");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Fecha retorno vacia");
                break;
            case 3:
                JOptionPane.showMessageDialog(this, "Pernota sin camptura");
                break;
            case 4:
                JOptionPane.showMessageDialog(this, "Empleado no seleccionado");
                break;
            case 5:
                JOptionPane.showMessageDialog(this, "Actividad vacia"); 
                break;
            case 6:
                JOptionPane.showMessageDialog(this, "Lugar no especificado");
                break;
              case 8:
                JOptionPane.showMessageDialog(this, "No se puede ser chofer de un vehiculo no pedido");
                break;
               case 9:
                JOptionPane.showMessageDialog(this, "La Fecha de salida no es valida");
                break;
                case 10:
                JOptionPane.showMessageDialog(this, "La Fecha de Retorno No es Valida");
                break;
        }
        
        
    }
    

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usuarioT = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        mj = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fecha2 = new com.toedter.calendar.JDateChooser();
        siPernota = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        noPernota = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        fecha1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Seleccionar = new JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jLabel9 = new javax.swing.JLabel();
        seleccionadoE = new javax.swing.JLabel();
        choferCheck = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        necesario = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        campoActividad = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        campoLugar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Seleccionar2 = new JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        etiquetaChofer = new javax.swing.JLabel();
        seleccionadoE2 = new javax.swing.JLabel();
        etiqueta2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        usuarioT.setBackground(new java.awt.Color(242, 48, 177));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir2.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/minus-sign.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });

        mj.setText("jLabel7");

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("NUEVA  SOLICITUD");

        javax.swing.GroupLayout usuarioTLayout = new javax.swing.GroupLayout(usuarioT);
        usuarioT.setLayout(usuarioTLayout);
        usuarioTLayout.setHorizontalGroup(
            usuarioTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(18, 18, 18)
                .addComponent(jLabel23)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuarioTLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mj)
                .addGap(138, 138, 138))
        );
        usuarioTLayout.setVerticalGroup(
            usuarioTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioTLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usuarioTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuarioTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel24)
                        .addComponent(jLabel23))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mj)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "LLENADO DE INFORMACION VIATICO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("FECHA DE SALIDA");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("FECHA DE LLEGADA");

        fecha2.setToolTipText("");
        fecha2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                fecha2MouseReleased(evt);
            }
        });

        siPernota.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        siPernota.setText("SI");
        siPernota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siPernotaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("PERNOTA");

        noPernota.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        noPernota.setText("NO");
        noPernota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noPernotaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N

        jLabel25.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel25.setText("EMPLEADO:");

        fecha1.setToolTipText("");

        Seleccionar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Seleccionar.setSelectionBackground(new java.awt.Color(255, 0, 153));
        Seleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeleccionarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Seleccionar);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 255));
        jLabel9.setText("EMPLEADO SELECCIONADO:");

        seleccionadoE.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seleccionadoE.setForeground(new java.awt.Color(255, 102, 255));
        seleccionadoE.setText("X");

        choferCheck.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        choferCheck.setText("EMPLEADO CHOFER");
        choferCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choferCheckActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("NECESITA VEHICULO");

        necesario.setSelected(true);
        necesario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                necesarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel25)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(choferCheck))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fecha1, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                                            .addComponent(fecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addComponent(siPernota)
                                        .addGap(18, 18, 18)
                                        .addComponent(noPernota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                                        .addComponent(necesario)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(seleccionadoE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(fecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(choferCheck))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(siPernota)
                        .addComponent(noPernota)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(necesario))
                .addGap(28, 28, 28)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(seleccionadoE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "ACTIVIDAD A REALIZAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        campoActividad.setColumns(20);
        campoActividad.setRows(5);
        jScrollPane2.setViewportView(campoActividad);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("DESCRIPCION ACTIVIDAD");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("LUGAR");

        Seleccionar2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Seleccionar2.setSelectionBackground(new java.awt.Color(255, 0, 153));
        Seleccionar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Seleccionar2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Seleccionar2);

        etiquetaChofer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiquetaChofer.setText("SELECCIONA UN CHOFER:");

        seleccionadoE2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        seleccionadoE2.setForeground(new java.awt.Color(255, 102, 255));
        seleccionadoE2.setText("X");

        etiqueta2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        etiqueta2.setForeground(new java.awt.Color(255, 102, 255));
        etiqueta2.setText("CHOFER SELECCIONADO:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(etiquetaChofer)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(etiqueta2)
                                .addGap(18, 18, 18)
                                .addComponent(seleccionadoE2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(campoLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaChofer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueta2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionadoE2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/send.png"))); // NOI18N
        jButton2.setText("ENVIAR SOLICITUD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addComponent(usuarioT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(usuarioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel24MouseClicked

    private void necesarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_necesarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_necesarioActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
        
        
       PersonalManejador empleado= new PersonalManejador();
       Seleccionar.setModel(empleado.Empleados());
       Seleccionar2.setModel(empleado.Choferes());
    }//GEN-LAST:event_formWindowActivated

    private void SeleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeleccionarMouseClicked
        // TODO add your handling code here:
         fila=Seleccionar.getSelectedRow(); 
        
        
         if(evt.getClickCount() == 1){
              seleccionadoE.setText(Seleccionar.getValueAt(fila, 1).toString());
              id_per=Seleccionar.getValueAt(fila, 0).toString();
         }
    }//GEN-LAST:event_SeleccionarMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
    SolictudesManejador manejador=new SolictudesManejador ();
    if(error()==false){
        ManejadorError(this.error);
    }else{
    pernotaValida();
    validaVehi();
    esChofer();
    
    ///validar fechas pendientes
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String FechaSalida = formato.format(fecha1.getDate());
        String FechaLlegada= formato.format(fecha2.getDate());
        ManejadorValidar validaFecha= new ManejadorValidar();
        
        
      int input = JOptionPane.showConfirmDialog(this,"Esta seguro que deasea enviar esta solicitud","Confirmar operacion",JOptionPane.YES_NO_CANCEL_OPTION);
        
    if(input==0){
        
        if(tipo==0){
       
    if(manejador.NuevaSolicitud(FechaSalida,campoLugar.getText() , campoActividad.getText(),estapernotando , FechaLlegada, mj.getText(), incluidoVehiculo, id_per, chofer)){
              JOptionPane.showMessageDialog(this, "Se a enviado un solicitud", "exito", HEIGHT); 
          this.dispose();
          this.setVisible(false);  
    }
    }else{
            if(manejador.NuevaSolicitudConChofer(FechaSalida,campoLugar.getText() , campoActividad.getText(),estapernotando , FechaLlegada, mj.getText(), incluidoVehiculo, id_per, chofer,id_chofer)){
              JOptionPane.showMessageDialog(this, "Se a enviado un solicitud", "exito", HEIGHT); 
          this.dispose();
          this.setVisible(false);  
        }
          }  
            
            
       
       
         
        
     
             
     
    }   
    }   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Seleccionar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Seleccionar2MouseClicked
        // TODO add your handling code here:
        
        
        fila2=Seleccionar2.getSelectedRow(); 
        
        
        if(evt.getClickCount() == 1){
              seleccionadoE2.setText(Seleccionar2.getValueAt(fila2, 1).toString());
              id_chofer=Seleccionar2.getValueAt(fila2, 0).toString();
         }
    }//GEN-LAST:event_Seleccionar2MouseClicked

    private void choferCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choferCheckActionPerformed
        // TODO add your handling code here:}
        
        
        
        
        if(choferCheck.isSelected()==true){
            
            this.m=!m;
            Seleccionar2.setVisible(m);
            etiquetaChofer.setVisible(m);
            etiqueta2.setVisible(m);
            seleccionadoE2.setVisible(m);
            
            
        }
        
        if(choferCheck.isSelected()==false){
            
            this.m=!m;
            Seleccionar2.setVisible(m);
            etiquetaChofer.setVisible(m);
            etiqueta2.setVisible(m);
            seleccionadoE2.setVisible(m);
            
        }
    }//GEN-LAST:event_choferCheckActionPerformed

    private void siPernotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siPernotaActionPerformed
        // TODO add your handling code here:
        
        
        if(siPernota.isSelected()){
            noPernota.setVisible(false);
        }
        if(siPernota.isSelected()==false){
            noPernota.setVisible(true);
        }
    }//GEN-LAST:event_siPernotaActionPerformed

    private void noPernotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noPernotaActionPerformed
        // TODO add your handling code here:
        if(noPernota.isSelected()){
            siPernota.setVisible(false);
        }
        if(noPernota.isSelected()==false){
            siPernota.setVisible(true);
        }
           
    }//GEN-LAST:event_noPernotaActionPerformed

    private void fecha2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fecha2MouseReleased
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_fecha2MouseReleased

    
    public void setVista(String fecha1,String fecha2,String actividad,String lugar,String perno,String necesita){
        
        
        
        
        
    }
    
    
    public void cambiaEti(String usu)
    {
        
        mj.setText(usu);
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevaSolicitud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Seleccionar;
    private javax.swing.JTable Seleccionar2;
    private javax.swing.JTextArea campoActividad;
    private javax.swing.JTextField campoLugar;
    private javax.swing.JCheckBox choferCheck;
    private javax.swing.JLabel etiqueta2;
    private javax.swing.JLabel etiquetaChofer;
    private com.toedter.calendar.JDateChooser fecha1;
    private com.toedter.calendar.JDateChooser fecha2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel mj;
    private javax.swing.JCheckBox necesario;
    private javax.swing.JCheckBox noPernota;
    private javax.swing.JLabel seleccionadoE;
    private javax.swing.JLabel seleccionadoE2;
    private javax.swing.JCheckBox siPernota;
    private javax.swing.JPanel usuarioT;
    // End of variables declaration//GEN-END:variables
}
