/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Reportes.ListaValeResguardo;
import basededatos.BDD;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.event.*;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Cherne
 */
public class Asignar extends javax.swing.JFrame {

    /**
     * Creates new form Asignar
     */
    BDD b;
    DefaultTableModel modelo;
    DefaultTableModel modelo1;
    TablaPersonal tp;
    ArrayList<String> asignados;
    TableModel pasar;
    String datos[][];
    String stocknn, stockoo;
    int id_cambio, id_cambio2, cont;
    int Cantidad,stockn,stocko;
    boolean stock;
    Clases.Validaciones v;
    Clases.MetodosG m;
    
    public Asignar() {

        initComponents();
        lblId.setVisible(false);
        v=new Clases.Validaciones();
        m=new Clases.MetodosG();
        tp= new TablaPersonal();
        id_cambio=0;
        id_cambio2=0;
        stock=false;
        stocknn=""; 
        stockoo = ""; 
        stockn=0;
        stocko=0;
        cont =0;
        b = new BDD();
        asignados = new ArrayList<>();
        String aux[][] = new String[0][0];
        iniciarTabla();
        tbl_productos1.setModel(new DefaultTableModel(
            aux,
            new String[]{
                "Folio","Categoria","Nombre","Marca","Modelo"
            }){
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            }
        
        );
        modelo1 = (DefaultTableModel)tbl_productos1.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buscatxt = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_productos = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_productos1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        btn_Guardar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tipouso = new javax.swing.JTextField();
        municipio = new javax.swing.JTextField();
        localidad = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buscatxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        buscatxt.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 153), null));

        btn_buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 51, 153));
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/loupe.png"))); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        tbl_productos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_productos.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                tbl_productosAncestorMoved(evt);
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
            }
        });
        tbl_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_productos);

        jButton11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 51, 153));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/error.png"))); // NOI18N
        jButton11.setText("CANCELAR");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        btnAgregar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 51, 153));
        btnAgregar.setText(">>");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnBorrar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 51, 153));
        btnBorrar.setText("<<");
        btnBorrar.setEnabled(false);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        tbl_productos1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tbl_productos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_productos1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productos1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_productos1);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        jButton12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 51, 153));
        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search-user-wearing-tie.png"))); // NOI18N
        jButton12.setText("ASIGNAR A");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        btn_Guardar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_Guardar.setForeground(new java.awt.Color(255, 51, 153));
        btn_Guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save.png"))); // NOI18N
        btn_Guardar.setText("GENERAR VALE");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        jLabel3.setText("TIPO DE USO:");

        jLabel7.setText("MUNICIPIO:");

        jLabel8.setText("LOCALIDAD:");

        tipouso.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tipouso.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 153), null));
        tipouso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipousoActionPerformed(evt);
            }
        });

        municipio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        municipio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 153), null));
        municipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                municipioActionPerformed(evt);
            }
        });

        localidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        localidad.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 102, 153), null));

        jButton13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton13.setForeground(new java.awt.Color(255, 51, 153));
        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search-user-wearing-tie.png"))); // NOI18N
        jButton13.setText("ASIGNAR COMODATO");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(buscatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBorrar)
                            .addComponent(btnAgregar))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(municipio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(localidad, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipouso))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)))
                .addComponent(lblId)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(lblId))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tipouso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(localidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(buscatxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn_buscar)
                                        .addComponent(jButton11)
                                        .addComponent(jButton12)
                                        .addComponent(btn_Guardar)
                                        .addComponent(jButton13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBorrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 51, 204));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ASIGNACIÓN DE PRODUCTOS");

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SISTEMA DE CONTROL DE INVENTARIO DEL IEEN");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/minus-sign.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salir2.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 375, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/IEE.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed
    private void iniciarTabla(){
        String query = "select p.folio_producto,c.nombre_categoria,p.nombre_producto,"
                + "p.marca_producto,p.modelo_producto from producto p inner join categoria c on p.id_categoria=c.id_categoria"
                + " where status_producto='Activo'";
        String[][] consulta = b.obtenerConsultas(query);
        modelo = new javax.swing.table.DefaultTableModel(
                consulta,
                new String[]{
                    "Folio", "Categoria", "Nombre", "Marca", "Modelo"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_productos.setModel(modelo);
    }
    private void tbl_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productosMouseClicked
        // TODO add your handling code here:
        
        /*if (evt.getClickCount() == 1 && !evt.isConsumed()) {
            btnAgregar.setEnabled(true);
            int rows = tbl_productos.rowAtPoint(evt.getPoint());
            String id = tbl_productos.getValueAt(rows, 0) + "";
            System.out.println(id);
            idCambio=Integer.parseInt(tbl_productos.getValueAt(rows, 0).toString());
        }*/
        
        id_cambio2=tbl_productos1.getRowCount();
        if(evt.getClickCount()==1 ){
            btnAgregar.setEnabled(true);
            int rows = tbl_productos.rowAtPoint(evt.getPoint());
            id_cambio=Integer.parseInt(tbl_productos.getValueAt(rows, 0).toString());           
        }
    }//GEN-LAST:event_tbl_productosMouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
       // pasar=tbl_productos1.getModel();
        //pasarDatos();
        //dispose();
        TablaPersonal  tablaPersonal=new TablaPersonal();
        tablaPersonal.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        if(jLabel1.getText().equals("")){
             javax.swing.JOptionPane.showMessageDialog(this,"Seleccione primero usuario a asignar");
             return;
        }
        if(id_cambio==0){
            javax.swing.JOptionPane.showMessageDialog(this,"Seleccione una fila");
             return;
        }
        int x = tbl_productos.getSelectedRow();
        /*modelo1.addRow(new Object[]{
            tbl_productos.getValueAt(x,0),
            tbl_productos.getValueAt(x,1),
            tbl_productos.getValueAt(x,2),
            tbl_productos.getValueAt(x,3)
        });*/
        cambiarDeTabla();
        asignados.add(tbl_productos.getValueAt(x,0)+"");

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
       // modelo1.removeRow(tbl_productos1.getSelectedRow());
       // asignados.remove(tbl_productos1.getSelectedRow());
        if(tbl_productos1.getRowCount()==0){
             javax.swing.JOptionPane.showMessageDialog(this, "No hay más elementos que borrar");
         }else{
        if(cont==0){
            id_cambio2=tbl_productos1.getRowCount()-1;
            //javax.swing.JOptionPane.showMessageDialog(this, id_cambio2+"");
            DefaultTableModel model =(DefaultTableModel) tbl_productos1.getModel(); 
            model.removeRow(id_cambio2);
        }
        else{
         DefaultTableModel model =(DefaultTableModel) tbl_productos1.getModel(); 
             model.removeRow(id_cambio2);
            cont=0;}
         }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tbl_productos1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productos1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1 ){
            btnBorrar.setEnabled(true);
            id_cambio2= tbl_productos1.rowAtPoint(evt.getPoint());
            //= Integer.parseInt(tbl_productos1.getValueAt(rows, 0)+"");
            cont++;
             
        }
    }//GEN-LAST:event_tbl_productos1MouseClicked

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        String cad="";
        try{cad = tbl_productos1.getValueAt(0,0)+"";}catch(ArrayIndexOutOfBoundsException ex){
            javax.swing.JOptionPane.showMessageDialog(this, "No hay ningún elemento seleccionado");
            return;
        }
        System.out.println(tbl_productos1.getColumnCount() + " -  Row"+ tbl_productos1.getRowCount());
        String [][] arr = new String[tbl_productos1.getRowCount()][tbl_productos1.getColumnCount()];
        for(int i = 0;i<tbl_productos1.getColumnCount();i++){   
            for(int j = 0; j<tbl_productos1.getRowCount();j++){
                arr[j][i]=tbl_productos1.getValueAt(j,i)+"";
            }
        }
        int r=0,s=0,t=0;
        if(tipouso.getText().equals("")){r=1;}
        if(municipio.getText().equals("")){s=1;}
        if(localidad.getText().equals("")){t=1;}
        String mes = "Campos en blanco";
        if(r==1){
            mes = mes + "\n Tipo de uso";
        }
        if(s==1){
            mes = mes + "\n Municipio";
        }
        if(t==1){
            mes = mes + "\n Localidad";
        }
        
        if(r==1 || s==1 || t==1){
            javax.swing.JOptionPane.showMessageDialog(this,mes);
            return;
        }
        
        List lista = new ArrayList();
        String[][] busqueda = b.obtenerConsultas(
                "select p.puesto from personal pe, puesto p "
              + "where puesto_id_puesto = id_puesto and id_personal ="+lblId.getText()+";");
        
        String[][] busqueda2 = b.obtenerConsultas(
                "select a.area from personal pe, puesto p, area a where \n" +
                "area_id_area = id_area and \n" +
                "puesto_id_puesto = id_puesto and \n" +
                "id_personal =" + lblId.getText() +";");
        
        
        try{
                String value0,value1,value2,value3;
                for(int i = 0;i<tbl_productos1.getRowCount();i++){
                    if(tbl_productos1.getValueAt(i, 0)==null)value0="";
                    else value0=tbl_productos1.getValueAt(i,0).toString();
                    if(tbl_productos1.getValueAt(i, 2)==null)value1="";
                    else value1=tbl_productos1.getValueAt(i,2).toString();
                    if(tbl_productos1.getValueAt(i, 3)==null)value2="";
                    else value2=tbl_productos1.getValueAt(i,3).toString();
                    if(tbl_productos1.getValueAt(i, 4)==null)value3="";
                    else value3=tbl_productos1.getValueAt(i,4).toString();
                    ListaValeResguardo listaedad = new ListaValeResguardo(
                            value0,value1,value2,value3);
                    lista.add(listaedad);
                }
                try {
                JasperReport reporte = (JasperReport)  JRLoader.loadObject("src/Reportes/ValeReguardo.jasper");
                
                Map parametro = new HashMap();
                parametro.put("nombre",jLabel1.getText());
                parametro.put("cargo", busqueda[0][0]);
                parametro.put("area", busqueda2[0][0]);
                parametro.put("tipo",tipouso.getText());
                parametro.put("muni", municipio.getText());
                parametro.put("localidad", localidad.getText());
                JasperPrint jprint = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(lista));
                JasperViewer jas = new JasperViewer(jprint,false); 
                jas.setVisible( true );
                }catch (JRException ex) {
                }
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null,"Error al generar el vale","ERROR",JOptionPane.WARNING_MESSAGE);
            }
        
        int id = m.getMax(b.obtenerConsultas("select id_asignacion from asignacion"));

    
        String [] insertar = new String [3];
        for(int i=0;i<tbl_productos1.getRowCount();i++){
            // folio    prodcto     marca   modelo  Cantidad
           // int id = m.getMax(b.obtenerConsultas("select id_asignacion from asignacion"));
            insertar[0]=id+"";
            String query="select id_producto from producto where folio_producto='"+tbl_productos1.getValueAt(i,0).toString()+"'";
            insertar[1]=b.getId(query)+"";
            insertar[2]=lblId.getText();        
            b.insertar("asignacion", insertar);
            b.execute("update producto set status_producto = 'Asignado' where folio_producto ='"+tbl_productos1.getValueAt(i,0).toString()+"'");
        }
        
        buscatxt.setText("");
        jLabel1.setText("");
        lblId.setText("");
        for(int i = tbl_productos1.getRowCount()-1; i>=0;i--){
            DefaultTableModel model =(DefaultTableModel) tbl_productos1.getModel(); 
            model.removeRow(i);
        }
        
        iniciarTabla();
        
        
        
        
    }//GEN-LAST:event_btn_GuardarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
    String criteriobus = buscatxt.getText();
    if(criteriobus.equals("")){ javax.swing.JOptionPane.showMessageDialog(this, "Campo de búsqueda vacío"); return; }
        String query = "select p.folio_producto,c.nombre_categoria,p.nombre_producto,"
                + "p.marca_producto,p.modelo_producto from producto p inner join categoria c on p.id_categoria=c.id_categoria"
                + " where status_producto='Activo' and where nombre_producto like '%"+criteriobus+"%'";
        String[][] consulta = b.obtenerConsultas(query);
        modelo = new javax.swing.table.DefaultTableModel(
                consulta,
                new String[]{
                    "Folio", "Categoria", "Nombre", "Marca", "Modelo"
                }
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tbl_productos.setModel(modelo);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void tbl_productosAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_tbl_productosAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_productosAncestorMoved

    private void tipousoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipousoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipousoActionPerformed

    private void municipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_municipioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_municipioActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:     
        if(tbl_productos1.getRowCount()==0)return;
        // TODO add your handling code here:  
        AsignarComodato asignar = new AsignarComodato(tbl_productos1.getModel(),Integer.parseInt(lblId.getText()));
        asignar.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        iniciarTabla();
    }//GEN-LAST:event_formWindowGainedFocus
    public void pasarDatos(){
        int x = tbl_productos.getRowCount();
        datos=new String[x][4];
        for(int i=0;i<x;i++){
           
            datos[i][0]=tbl_productos.getValueAt(i,0)+"";
            datos[i][1]=tbl_productos.getValueAt(i,1)+"";
            datos[i][2]=tbl_productos.getValueAt(i,2)+"";
            datos[i][3]=tbl_productos.getValueAt(i,3)+"";
        }
    }
     private void cambiarDeTabla(){
        if(id_cambio==0)javax.swing.JOptionPane.showMessageDialog(this, "Seleccione una fila");
        String query="select p.folio_producto,c.nombre_categoria,p.nombre_producto,p.marca_producto,p.modelo_producto from producto p inner join categoria c "
                        + "on p.id_categoria=c.id_categoria where p.id_producto='"+id_cambio+"'";
        String [][] busqueda = (b.obtenerConsultas(query));
        String [] nuevo=new String[5];
        nuevo[0]=busqueda[0][0];
        nuevo[1]=busqueda[0][1];
        nuevo[2]=busqueda[0][2];
        nuevo[3]=busqueda[0][3];
        nuevo[4]=busqueda[0][4];
        DefaultTableModel model =(DefaultTableModel) tbl_productos1.getModel(); 
        model.addRow(nuevo); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asignar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asignar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JTextField buscatxt;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblId;
    private javax.swing.JTextField localidad;
    private javax.swing.JTextField municipio;
    private javax.swing.JTable tbl_productos;
    private javax.swing.JTable tbl_productos1;
    private javax.swing.JTextField tipouso;
    // End of variables declaration//GEN-END:variables
}
