/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.MetodosG;
import basededatos.BDD;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author pasto
 */
public class ModificarU extends javax.swing.JFrame {

    /**
     * Creates new form ModificarU
     */
    String apellido,nombre,idarea,idpuestos,idPersonal;
    BDD b;
    boolean bandera;
    MetodosG m;
    public ModificarU(String ap, String nombre) {
        m = new MetodosG();
        idpuestos="";
        b= new BDD();
        bandera=false;
        apellido=ap;
        this.nombre=nombre;
        initComponents();
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(b.convertir2d1d
        (b.obtenerConsultas("select area from area order by area"))));
        fillIn();
    }

    public ModificarU() {
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        auNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        auApellidoP = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        auApellidoM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        auCurp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        auRFC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        auNoLicencia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        auNoCredencial = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        auTelefono = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        auCalle = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        auNum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        auColonia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        auCp = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        puesto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 51, 204));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MODIFICACIÓN DE USUARIOS");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/minus-sign.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/salir2.png"))); // NOI18N
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setText("NOMBRE:");

        auNombre.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auNombre.setNextFocusableComponent(auApellidoP);
        auNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auNombreFocusGained(evt);
            }
        });
        auNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auNombreKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("APELLIDO PATERNO:");

        auApellidoP.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auApellidoP.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auApellidoP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auApellidoPFocusGained(evt);
            }
        });
        auApellidoP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auApellidoPKeyTyped(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setText("APELLIDO MATERNO:");

        auApellidoM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auApellidoM.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auApellidoM.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auApellidoMFocusGained(evt);
            }
        });
        auApellidoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                auApellidoMActionPerformed(evt);
            }
        });
        auApellidoM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auApellidoMKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("CURP:");

        auCurp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auCurp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auCurp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auCurpFocusGained(evt);
            }
        });
        auCurp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auCurpKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auCurpKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("RFC:");

        auRFC.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auRFC.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auRFC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auRFCFocusGained(evt);
            }
        });
        auRFC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auRFCKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auRFCKeyTyped(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("NO. LICENCIA DE CONDUCIR:");

        auNoLicencia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auNoLicencia.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auNoLicencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auNoLicenciaFocusGained(evt);
            }
        });
        auNoLicencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                auNoLicenciaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auNoLicenciaKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("NO. CREDENCIAL DE ELECTOR:");

        auNoCredencial.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auNoCredencial.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auNoCredencial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auNoCredencialFocusGained(evt);
            }
        });
        auNoCredencial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auNoCredencialKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("FECHA DE NACIMIENTO:");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setText("TELÉFONO:");

        auTelefono.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auTelefono.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auTelefonoFocusGained(evt);
            }
        });
        auTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auTelefonoKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setText("CALLE:");

        auCalle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auCalle.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auCalle.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auCalleFocusGained(evt);
            }
        });
        auCalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auCalleKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("NÚMERO:");

        auNum.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auNum.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auNum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auNumFocusGained(evt);
            }
        });
        auNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auNumKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("COLONIA:");

        auColonia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auColonia.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auColonia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auColoniaFocusGained(evt);
            }
        });
        auColonia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auColoniaKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("CÓDIGO POSTAL:");

        auCp.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        auCp.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        auCp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                auCpFocusGained(evt);
            }
        });
        auCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                auCpKeyTyped(evt);
            }
        });

        jDateChooser1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        jDateChooser1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/save.png"))); // NOI18N
        jButton9.setText("GUARDAR");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/eraser.png"))); // NOI18N
        jButton10.setText("LIMPIAR");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/error.png"))); // NOI18N
        jButton11.setText("CANCELAR");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        puesto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        puesto.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), null));
        puesto.setNextFocusableComponent(auNombre);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("PUESTO:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("AREA:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(36, 36, 36)
                .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(265, 265, 265))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(auApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(auNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(auApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(auRFC)
                            .addComponent(auCurp)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(30, 30, 30)
                        .addComponent(jButton10)
                        .addGap(29, 29, 29)
                        .addComponent(jButton11)
                        .addGap(300, 300, 300))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(18, 18, 18)
                                        .addComponent(auCp, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(auColonia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(226, 226, 226))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                        .addComponent(auCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel17))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(auNoCredencial)
                                                .addComponent(auNoLicencia, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(18, 18, 18))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                                    .addComponent(jLabel9)
                                                    .addGap(32, 32, 32)))
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(auNum, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(auTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(auNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(auNoCredencial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(auApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(auApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(auCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(auRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(auNoLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(auCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(auColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(auNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel20)
                            .addComponent(auCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(auTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(jButton10)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 974, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fillIn(){
        String query = "select p.id_personal,p.nombre,p.apellido_pa,p.apellido_ma,p.domicilio,p.domicilio_numero,p.domicilio_colonia,p.codigo_pos,p.telefono,p.fechanac_personal,p.curp,p.rfc,p.nolic_personal,p.nocredencial_personal,a.area,pu.puesto,p.puesto_id_puesto from personal p inner join puesto pu on p.puesto_id_puesto=pu.id_puesto inner join area a on pu.area_id_area=a.id_area where p.nombre = '"+nombre+"' and p.apellido_pa = '"+apellido+"'";
        String [][] consulta = b.obtenerConsultas(query);
        auNombre.setText(consulta[0][1]);
        auApellidoP.setText(consulta[0][2]);
        auApellidoM.setText(consulta[0][3]);
        auCalle.setText(consulta[0][4]);
        auNum.setText(consulta[0][5]);
        auColonia.setText(consulta[0][6]);
        auCp.setText(consulta[0][7]);
        auTelefono.setText(consulta[0][8]);
        java.util.Date date2=null;
        try{date2 = new SimpleDateFormat("yyyy-MM-dd").parse(consulta[0][9]);}catch(ParseException e){}
        jDateChooser1.setDate(date2);
        auCurp.setText(consulta[0][10]);
        auRFC.setText(consulta[0][11]);
        auNoLicencia.setText(consulta[0][12]);
        auNoCredencial.setText(consulta[0][13]);
        jComboBox2.setSelectedItem(consulta[0][14]);
        puesto.setText(consulta[0][15]);
        idPersonal=consulta[0][0];
        idpuestos=consulta[0][16];
    }
    
    private void update(){
        if(bandera){
            int idArea = b.getId("select id_area from areas where nombre_area='"+jComboBox2.getSelectedItem().toString()+"'");
            b.execute("update puesto set area_id_area ='"+idArea+"' where id_puesto = '"+idpuestos+"'");
        }    
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fecha = sdf.format(jDateChooser1.getDate());
        Date when = new Date();
        if(jDateChooser1.getDate().after(when)){return;}
        String update = "nombre ='"+m.jtextfield(auNombre)+"', "
                + "apellido_pa ='"+m.jtextfield(auApellidoP)+"', "
                + "apellido_ma ='"+m.jtextfield(auApellidoP)+"', "
                + "domicilio ='"+m.jtextfield(auApellidoP)+"', "
                + "domicilio_numero ='"+m.jtextfield(auApellidoP)+"', "
                + "domicilio_colonia ='"+m.jtextfield(auApellidoP)+"', "
                + "codigo_pos ='"+m.jtextfield(auApellidoP)+"', "
                + "telefono ='"+m.jtextfield(auApellidoP)+"', "
                + "fechanac_personal ='"+fecha+"', "
                + "curp ='"+m.jtextfield(auApellidoP)+"', "
                + "rfc ='"+m.jtextfield(auApellidoP)+"', "
                + "nolic_personal ='"+m.jtextfield(auApellidoP)+"', "
                + "nocredencial_personal ='"+m.jtextfield(auApellidoP)+"'";
        b.execute("update personal set "+update+" where id_personal ='"+idPersonal+"'");
        String update2 = "puesto ='"+m.jtextfield(puesto)+"'";
        b.execute("update puesto set "+update2+" where id_puesto ='"+idpuestos+"'");
                
    }
    
    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jLabel14MouseClicked

    private void auNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auNombreFocusGained
        // TODO add your handling code here:
        auNombre.setBackground(Color.white);
    }//GEN-LAST:event_auNombreFocusGained

    private void auApellidoPFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auApellidoPFocusGained
        // TODO add your handling code here:
        auApellidoP.setBackground(Color.white);
    }//GEN-LAST:event_auApellidoPFocusGained

    private void auApellidoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_auApellidoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_auApellidoMActionPerformed

    private void auApellidoMFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auApellidoMFocusGained
        // TODO add your handling code here:
        auApellidoM.setBackground(Color.white);
    }//GEN-LAST:event_auApellidoMFocusGained

    private void auCurpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auCurpFocusGained
        // TODO add your handling code here:
        auCurp.setBackground(Color.white);
    }//GEN-LAST:event_auCurpFocusGained

    private void auCurpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auCurpKeyReleased
        // TODO add your handling code here:
        auCurp.setText(auCurp.getText().toUpperCase());
    }//GEN-LAST:event_auCurpKeyReleased

    private void auCurpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auCurpKeyTyped
        // TODO add your handling code here:
        if(auCurp.getText().length()>=18){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') &&(c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auCurpKeyTyped

    private void auRFCFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auRFCFocusGained
        // TODO add your handling code here:
        auRFC.setBackground(Color.white);
    }//GEN-LAST:event_auRFCFocusGained

    private void auRFCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auRFCKeyReleased
        // TODO add your handling code here:
        auRFC.setText(auRFC.getText().toUpperCase());
    }//GEN-LAST:event_auRFCKeyReleased

    private void auRFCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auRFCKeyTyped
        // TODO add your handling code here:
        if(auRFC.getText().length()>=13){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') &&(c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auRFCKeyTyped

    private void auNoLicenciaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auNoLicenciaFocusGained
        // TODO add your handling code here:
        auNoLicencia.setBackground(Color.white);
    }//GEN-LAST:event_auNoLicenciaFocusGained

    private void auNoLicenciaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auNoLicenciaKeyReleased
        // TODO add your handling code here:
        auNoLicencia.setText(auNoLicencia.getText().toUpperCase());
    }//GEN-LAST:event_auNoLicenciaKeyReleased

    private void auNoLicenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auNoLicenciaKeyTyped
        // TODO add your handling code here:
       if(auNoLicencia.getText().length()>=8){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') &&(c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auNoLicenciaKeyTyped

    private void auNoCredencialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auNoCredencialFocusGained
        // TODO add your handling code here:
        auNoCredencial.setBackground(Color.white);
    }//GEN-LAST:event_auNoCredencialFocusGained

    private void auNoCredencialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auNoCredencialKeyTyped
        // TODO add your handling code here:
        if(auNoCredencial.getText().length()>=10){
            evt.consume();
        }
    }//GEN-LAST:event_auNoCredencialKeyTyped

    private void auTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auTelefonoFocusGained
        // TODO add your handling code here:
        auTelefono.setBackground(Color.white);
    }//GEN-LAST:event_auTelefonoFocusGained

    private void auTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auTelefonoKeyTyped
        // TODO add your handling code here:
        if(auTelefono.getText().length()>=10){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auTelefonoKeyTyped

    private void auCalleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auCalleFocusGained
        // TODO add your handling code here:
        auCalle.setBackground(Color.white);
    }//GEN-LAST:event_auCalleFocusGained

    private void auNumFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auNumFocusGained
        // TODO add your handling code here:
        auNum.setBackground(Color.white);
    }//GEN-LAST:event_auNumFocusGained

    private void auColoniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auColoniaFocusGained
        // TODO add your handling code here:
        auColonia.setBackground(Color.white);
    }//GEN-LAST:event_auColoniaFocusGained

    private void auCpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_auCpFocusGained
        // TODO add your handling code here:
        auCp.setBackground(Color.white);
    }//GEN-LAST:event_auCpFocusGained

    private void auCpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auCpKeyTyped
        // TODO add your handling code here:
        if(auCp.getText().length()>=5){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auCpKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        /*int contErr=0;
        Clases.Validaciones v= new Clases.Validaciones();
        if(v.soloLetras(auNombre.getText())){
            contErr++;
            auNombre.setBackground(Color.PINK);

        }
        if(v.soloLetras(auApellidoP.getText())){
            contErr++;
            //asNombre.setText("*");
            auApellidoP.setBackground(Color.PINK);
        }
        if(v.soloLetras(auApellidoM.getText())){
            contErr++;
            //asMarca.setText("*");
            auApellidoM.setBackground(Color.PINK);
        }
        if(auCurp.getText().length()!=18){
            contErr++;
            //asModelo.setText("*");
            auCurp.setBackground(Color.PINK);
        }
        if(auRFC.getText().length()!=13){
            contErr++;
            //asNoSerie.setText("*");
            auRFC.setBackground(Color.PINK);
        }
        if(v.soloNumeros(auNoCredencial.getText()) || auNoCredencial.getText().length()!=10){
            contErr++;
            //asColor.setText("*");
            auNoCredencial.setBackground(Color.PINK);
        }
        if(auNoLicencia.getText().length()!=8){
            contErr++;
            //asNoFact.setText("*");
            auNoLicencia.setBackground(Color.PINK);
        }
        if(v.estaVacio(auCalle.getText())){
            contErr++;
            //asImporte.setText("*");
            auCalle.setBackground(Color.PINK);
        }
        ///////////////
        if(v.soloNumeros(auTelefono.getText()) || auTelefono.getText().length()!=10){
            contErr++;
            //asNoSerie.setText("*");
            auTelefono.setBackground(Color.PINK);
        }
        if(v.estaVacio(auColonia.getText())){
            contErr++;
            //asColor.setText("*");
            auColonia.setBackground(Color.PINK);
        }
        if(v.soloNumeros(auNum.getText())){
            contErr++;
            //asNoFact.setText("*");
            auNum.setBackground(Color.PINK);
        }
        if(v.soloNumeros(auCp.getText()) || auCp.getText().length()!=5){
            contErr++;
            //asImporte.setText("*");
            auCp.setBackground(Color.PINK);
        }
        if(contErr>0){
            javax.swing.JOptionPane.showMessageDialog(null,"Campos vacios/invalidos");

        }else{*/
            update();
            JOptionPane.showMessageDialog(this, "Se han guardado los cambios");
            this.dispose();
    //}
        //contErr=0;
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
         // TODO add your handling code here:
         bandera=true;
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void auNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auNombreKeyTyped
        // TODO add your handling code here:
        if(auNombre.getText().length()>20){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && c!='ñ' && c!='Ñ' && c!='á'
                && c!='é' && c!='í' && c!='ó' && c!='ú' && c!=' ' 
                && c!='Á' && c!='É' && c!='Í' && c!='Ú' && c!='Ó' && c!=' ') evt.consume();
    }//GEN-LAST:event_auNombreKeyTyped

    private void auApellidoPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auApellidoPKeyTyped
        // TODO add your handling code here:
        if(auApellidoP.getText().length()>20){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && c!='ñ' && c!='Ñ' && c!='á'
                && c!='é' && c!='í' && c!='ó' && c!='ú' && c!=' ' 
                && c!='Á' && c!='É' && c!='Í' && c!='Ú' && c!='Ó' && c!=' ') evt.consume();
    }//GEN-LAST:event_auApellidoPKeyTyped

    private void auApellidoMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auApellidoMKeyTyped
        // TODO add your handling code here:
        if(auApellidoM.getText().length()>20){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && c!='ñ' && c!='Ñ' && c!='á'
                && c!='é' && c!='í' && c!='ó' && c!='ú' && c!=' ' 
                && c!='Á' && c!='É' && c!='Í' && c!='Ú' && c!='Ó' && c!=' ') evt.consume();
    }//GEN-LAST:event_auApellidoMKeyTyped

    private void auCalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auCalleKeyTyped
        // TODO add your handling code here:
        if(auCalle.getText().length()>40){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && c!='ñ' && c!='Ñ' && c!='á'
                && c!='é' && c!='í' && c!='ó' && c!='ú' && c!=' ' 
                && c!='Á' && c!='É' && c!='Í' && c!='Ú' && c!='Ó' && c!=' ' &&(c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auCalleKeyTyped

    private void auNumKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auNumKeyTyped
        // TODO add your handling code here:
        if(auNum.getText().length()>6){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auNumKeyTyped

    private void auColoniaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_auColoniaKeyTyped
        // TODO add your handling code here:
        if(auColonia.getText().length()>30){
            evt.consume();
        }
        char c = evt.getKeyChar();
        if((c<'a' || c>'z') && (c<'A' || c>'Z') && c!='ñ' && c!='Ñ' && c!='á'
                && c!='é' && c!='í' && c!='ó' && c!='ú' && c!=' ' 
                && c!='Á' && c!='É' && c!='Í' && c!='Ú' && c!='Ó' && c!=' ' &&(c<'0' || c>'9')) evt.consume();
    }//GEN-LAST:event_auColoniaKeyTyped

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        Date date = new Date();
        if(jDateChooser1.getDate()==null)return;
        if(jDateChooser1.getDate().after(date)){JOptionPane.showMessageDialog(this, "Fecha posterior a la actual");}
    }//GEN-LAST:event_jDateChooser1PropertyChange
    private void limpiar(){
        auNombre.setText("");
        auApellidoP.setText("");
        auApellidoM.setText("");
        auCalle.setText("");
        auNum.setText("");
        auColonia.setText("");
        auCp.setText("");
        auTelefono.setText("");
        jDateChooser1.setCalendar(null);
        auCurp.setText("");
        auRFC.setText("");
        auNoLicencia.setText("");
        auNoCredencial.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField auApellidoM;
    private javax.swing.JTextField auApellidoP;
    private javax.swing.JTextField auCalle;
    private javax.swing.JTextField auColonia;
    private javax.swing.JTextField auCp;
    private javax.swing.JTextField auCurp;
    private javax.swing.JTextField auNoCredencial;
    private javax.swing.JTextField auNoLicencia;
    private javax.swing.JTextField auNombre;
    private javax.swing.JTextField auNum;
    private javax.swing.JTextField auRFC;
    private javax.swing.JTextField auTelefono;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField puesto;
    // End of variables declaration//GEN-END:variables
}
